In [1]:
import data_parsing
import numpy as np


input_data = '../data/day6_data.txt'
pod_math = data_parsing.read_2dmap_to_numpy(input_data, split_by_spaces=True)



num_cols = pod_math.shape[1]

results = []

for col in range(num_cols):
    operator = pod_math[-1,col]
    # since it's numpy, just cast the array to integers from strings
    # because numbers wind up hella big, we need to clearly specify
    # early on that we want to use 64 bit integers, not 32 bit
    # which numpy will use by default
    digits = pod_math[:-1, col].astype(np.int64)

    # upside is operators are multiplication and addition
    # aka product and sum
    # since everything is a numpy array
    # stick to using numpy to do the math
    # even though product and sum are standard operators

    if operator == '*':
        r = np.prod(digits)

    if operator == '+':
        r = np.sum(digits)

    results.append(r)

results = np.array(results, dtype='int64')

print ('Part 1: ', np.sum(results) )

Part 1:  6299564383938


In [ ]:
pod_math2 = data_parsing.read_2dmap_to_numpy(input_data, split_by_spaces=False)

col_breaks = []
# make an array of the index positions where every row has white space
# because we need to retain the layout grid to make new values along the 
# vertical axis
breaks = np.where(np.all(pod_math2 == ' ', axis=0) == True)[0]
results = []

for equations in range(len(breaks)+1):
    new_digits = None

    # the slicing here could probably be more elegant....or not
    if equations == 0:
        digits_slice = pod_math2[0:-1, 0:breaks[equations]]
        operator_slice = pod_math2[-1, 0:breaks[equations]]
    if ((equations != 0) & (equations != len(breaks))):
        digits_slice = pod_math2[0:-1, breaks[equations-1]+1:breaks[equations]]
        operator_slice = pod_math2[-1, breaks[equations-1]+1:breaks[equations]]
    if (equations == len(breaks)):
        digits_slice = pod_math2[0:-1, breaks[equations-1]+1:]
        operator_slice = pod_math2[-1,breaks[equations-1]+1: ]


    # shape[1] is because we want new numerical values
    # for each column's worth of digits and numpy's shape
    # function lists row,col since it's row major
    holding = np.empty((digits_slice.shape[1]), dtype='int64')

    for col in range(digits_slice.shape[1]):
        holding[col]= int(''.join(digits_slice[:,col]))

    if '*' in operator_slice:
        r = np.prod(holding)
    if '+' in operator_slice:
        r = np.sum(holding)
    results.append(r)

results = np.array(results, dtype='int64')
print ('Part 2: ', np.sum(results))

[['5' '8' ' ' ' ']
 ['6' '7' '2' '4']
 ['1' '3' '1' '1']
 ['6' '2' '4' '5']] ['+' ' ' ' ' ' ']
(4, 4)
0 5616
1 8732
2 214
3 415
[5616 8732  214  415]
[['2' ' ']
 ['4' '8']
 ['1' '3']
 ['3' '7']] ['*' ' ']
(4, 2)
0 2413
1 837
[2413  837]
[['6' '6']
 ['3' '2']
 ['8' '8']
 ['9' '5']] ['*' ' ']
(4, 2)
0 6389
1 6285
[6389 6285]
[['9' '7']
 ['3' ' ']
 ['1' ' ']
 ['7' ' ']] ['+' ' ']
(4, 2)
0 9317
1 7
[9317    7]
[['7' '6']
 ['9' '6']
 ['5' '3']
 ['6' ' ']] ['*' ' ']
(4, 2)
0 7956
1 663
[7956  663]
[['6' '2']
 ['2' '4']
 ['6' '8']
 ['5' '1']] ['*' ' ']
(4, 2)
0 6265
1 2481
[6265 2481]
[[' ' '3' '2']
 [' ' '9' '7']
 ['8' '1' '9']
 ['7' '3' '9']] ['+' ' ' ' ']
(4, 3)
0 87
1 3913
2 2799
[  87 3913 2799]
[['4' '5']
 ['3' '8']
 ['5' '9']
 ['2' '4']] ['+' ' ']
(4, 2)
0 4352
1 5894
[4352 5894]
[[' ' ' ' '1' '6']
 [' ' '5' '6' '4']
 [' ' '8' '5' '7']
 ['4' '2' '6' '7']] ['+' ' ' ' ' ' ']
(4, 4)
0 4
1 582
2 1656
3 6477
[   4  582 1656 6477]
[['2' '6']
 ['1' '3']
 ['1' '3']
 ['1' '8']] ['*' ' ']
(4, 2)